### ISSUE TITLE
Running npm test on Windows

### ISSUE THREAD

**Issue by MSebastian2021** [adaltas/dsti-devops-2022-spring#2]
## Description

Error message: 

> ece-userapi@1.0.0 test
> ./node_modules/.bin/mocha test/*.js

'.' is not recognized as an internal or external command,
operable program or batch file.

## To Reproduce
 
Go to the lab: https://github.com/adaltas/dsti-devops-2022-spring/tree/master/courses/devops/modules/03.continuous-testing/lab#testing

## Expected behavior

Should display:

`> ece-userapi@1.0.0 test
> mocha test/*.js

Server listening the port 8080

  Configure
    ✔ load default json configuration file
    ✔ load custom configuration

  Redis
    ✔ should connect to Redis

  User
    Create
      ✔ create a new user
      ✔ passing wrong user parameters

  User REST API
    POST /user
      ✔ create a new user
      ✔ pass wrong parameters

  7 passing (40ms)`

## Environment:

    OS: Windows
    Version 10

## Solution

Execute `npm install mocha --save-dev` first before running `npm test`

**Comment by sergkudinov** [comment]
This is because you have you CLI misconfigured on Windows.

You can also try to reconfigure the `test` script to the following:

```
  "scripts": {
    "test": "mocha test/*.js"
  },
```
